### ISSUE TITLE
Leider können wir ohne deine Location nicht viel anfangen. :/

### ISSUE THREAD

**Issue by vv01f** [filter1/magdego-homepage#2]
Dann fragt mich nach den Koordinaten ;)
Unter Demo gab es bereits drei Buttons, zusätzlich ggf. eine Frage nach Haltestellen oder zumindest einer Liste von Straßennamen (min. 1), Stadt ... und Ermittlung der Geodaten daraus

**Comment by filter1** [comment]
Ja, gute Idee. Werden wir umsetzten!
